### ISSUE TITLE
Plugin does not automatically handle `extra_css` and `extra_javascript`

### ISSUE THREAD

**Issue by Archmonger** [byrnereese/mkdocs-minify-plugin#33]
The readme says:
> When using minify_js or minify_css, you don't have to modify the extra_javascript or extra_css entries in your mkdocs.yml file. The plugins automatically takes care of that.

However, this automatic handling does not appear to work anymore.

```bash
Traceback (most recent call last):
  File "C:\Users\Username\Repositories\reactpy-django\.venv\lib\site-packages\mkdocs\livereload\__init__.py", line 190, in _build_loop
    func()
  File "C:\Users\Username\Repositories\reactpy-django\.venv\lib\site-packages\mkdocs\commands\serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "C:\Users\Username\Repositories\reactpy-django\.venv\lib\site-packages\mkdocs\commands\build.py", line 354, in build
    config.plugins.on_post_build(config=config)
  File "C:\Users\Username\Repositories\reactpy-django\.venv\lib\site-packages\mkdocs\plugins.py", line 542, in on_post_build
    return self.run_event('post_build', config=config)
  File "C:\Users\Username\Repositories\reactpy-django\.venv\lib\site-packages\mkdocs\plugins.py", line 509, in run_event
    result = method(**kwargs)
  File "C:\Users\Username\Repositories\reactpy-django\.venv\lib\site-packages\mkdocs_minify_plugin\plugin.py", line 219, in on_post_build
    self._minify("js", config)
  File "C:\Users\Username\Repositories\reactpy-django\.venv\lib\site-packages\mkdocs_minify_plugin\plugin.py", line 90, in _minify
    file.write(self.path_to_data[file_path])
KeyError: 'assets/js/main.js'
```

**Comment by DesiresAreGrey** [comment]
I'm having this issue too
