### ISSUE TITLE
Latest commit breaks python3 compatibility

### ISSUE THREAD

**Issue by fj-sanchez** [byrnereese/mkdocs-minify-plugin#8]
In python3 the print syntax is different and requires parenthesis:

```
 Traceback (most recent call last):
   File "/usr/local/bin/mkdocs", line 8, in <module>
     sys.exit(cli())
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
     return self.main(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
     rv = self.invoke(ctx)
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
     return callback(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/mkdocs/__main__.py", line 162, in build_command
     site_dir=site_dir
   File "/usr/local/lib/python3.7/site-packages/mkdocs/config/base.py", line 197, in load_config
     errors, warnings = cfg.validate()
   File "/usr/local/lib/python3.7/site-packages/mkdocs/config/base.py", line 107, in validate
     run_failed, run_warnings = self._validate()
   File "/usr/local/lib/python3.7/site-packages/mkdocs/config/base.py", line 62, in _validate
     self[key] = config_option.validate(value)
   File "/usr/local/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 132, in validate
     return self.run_validation(value)
   File "/usr/local/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 572, in run_validation
     plgins[item] = self.load_plugin(item, cfg)
   File "/usr/local/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 580, in load_plugin
     Plugin = self.installed_plugins[name].load()
   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
     return self.resolve()
   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
     module = __import__(self.module_name, fromlist=['__name__'], level=0)
   File "/usr/local/lib/python3.7/site-packages/mkdocs_minify_plugin/plugin.py", line 33
     print "htmlmin option " + key + " not recognized"
                           ^
 SyntaxError: Missing parentheses in call to 'print'. Did you mean print("htmlmin option " + key + " not recognized")?
                           ^
```

**Comment by byrnereese** [comment]
Fixed in 0.2.3
